FROM arm64v8/alpine:3.9

RUN apk add --no-cache bash && \
    apk add --no-cache ca-certificates && \
    apk add --no-cache tzdata && \
    ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
COPY tcp-proxy /tcp-proxy
WORKDIR /
ENTRYPOINT ["./tcp-proxy"]
